<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OCSSF_SGFAInputField</name>
   <tag></tag>
   <elementGuidId>b172bb62-8fa8-4b1a-9cab-822d58b2feec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@name='sgfaNumField'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@name='sgfaNumField'])[2]</value>
   </webElementProperties>
</WebElementEntity>
