<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OCSSF_noOfStructureInputField</name>
   <tag></tag>
   <elementGuidId>af3543e2-8360-4c8a-b417-6f0ec2853e61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@name='noOfstrucNumField'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@name='noOfstrucNumField'])[2]</value>
   </webElementProperties>
</WebElementEntity>
