<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WCSSF_SGFAInputField</name>
   <tag></tag>
   <elementGuidId>56193c9d-4350-4dd2-84aa-27a1821d9b91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@name='sgfaNumField'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@name='sgfaNumField'])[1]</value>
   </webElementProperties>
</WebElementEntity>
